### PR TITLE
Remove RubyZip Fix

### PR DESCRIPTION
**Pull request by mvz**
This fix no longer seems needed with rubyzip 2.x and breaks other gems.

### CODE REVIEW

**Review by boblail — APPROVED** [review]
👍  Thank you!

**Comment by mvz** [comment]
@boblail any news on this?

**Comment by mvz** [comment]
Thanks @boblail!

**Comment by mvz** [comment]
@boblail and @kobsy, any chance of creating a release that includes this change? I would really appreciate it!

**Pull request merged**
